### ISSUE TITLE
Showing in Full Screen mode while watching video

### ISSUE THREAD

**Issue by Martii** [sebaro/SaveTube#6] opened 2016-08-13 16:01 UTC
So https://github.com/sebaro/SaveTube/commit/bd82f695f413edaf616a5dc978ce241c501109c1 seems to be showing on Windows 7 full screen.

Is this intended behavior? 

Took me a bit to see where it was placed too... used to it under video but now pinned in lower right corner. Handy there. :)

TIA

**Comment by sebaro** [comment] 2016-08-13 17:21
I assume Pale Moon.

**Comment by Martii** [comment] 2016-08-13 18:08
Yup... good guess... had to contact the user. :)

**Comment by sebaro** [comment] 2016-08-14 05:11
Most of the time is PM.

Try with "1999999999" instead of "9999999999" on line 270.

**Comment by Martii** [comment] 2016-08-14 13:50
That works on Linux and Windows of PM. So CSS `z-index` has a maximum value in `Mozilla/5.0 (X11; Linux x86_64; rv:2.1) Gecko/20100101 Goanna/20160629 PaleMoon/26.3.3` ?

**Comment by Martii** [comment] 2016-08-14 14:21
I wonder if the JavaScript property could be tested in your element property abstract to see if it throws and error and/or is actually set to that value. Made an issue on PMs site as you can see.

**Comment by sebaro** [comment] 2016-08-14 14:42
I don't think setting this style property (or any other) to any value will throw an error.

Each browser has a min/max value, most use signed 32-bit values, −2147483648 to +2147483647, and if one if the value is exceeded the values is changed to the min/max value or 0.

YouTube uses "1999999999" for the header (logo, search).

I think the browser should cover all elements when in full screen no matter what z-Index values are set, that's what happens in Chromium/Firefox.

**Comment by Martii** [comment] 2016-08-14 14:45
See [PM support response](https://github.com/MoonchildProductions/Pale-Moon/issues/481#issuecomment-239677208) too.

**Comment by sebaro** [comment] 2016-08-14 14:52
PM changes to 2147483647 too, so the issue is not this value but their full-screen implementation.
With "2147483646" it's OK but with "2147483647" it's not.

**Comment by Martii** [comment] 2016-08-14 15:04
Hmm well... I'll mirror that over there as conciliation but my friend would definitely like to not see it in full screen and he's probably not going to want to edit the script every release of this .user.js. I can do it for him when I'm here though.

**Comment by Martii** [comment] 2016-08-14 16:25
So I'll look up the specification for this when I get back to dev station next week and see what I can find the "official default".

In the meantime would it be possible to alter YouTubes z-index per:

> YouTube uses "1999999999" for the header (logo, search).

??

**Comment by sebaro** [comment] 2016-08-14 17:20
I'll change the z-Index in the script to 2 billion, for PM 26.3.3 (Linux) the full-screen is fine for values <= 2147483646. let me know if you find issues with this value.

**Comment by Martii** [comment] 2016-08-14 18:04
> 2147483646. let me know if you find issues with this value.

No issues detected e.g. seems to work under *nix and Windows. Thanks

**Comment by sebaro** [comment] 2016-08-15 08:58
#

**Comment by sebaro** [comment] 2016-08-15 08:59
Change committed.

**Comment by Martii** [comment] 2016-08-15 16:08
Just another way of doing that 32 bit maximum number constant if you wish... remember I teach some too *(and learn myself as well)*

**Comment by sebaro** [comment] 2016-08-15 17:42
I'll use the 2 billion string I don't want to cause other issues with other browsers.

**Comment by Martii** [comment] 2016-08-15 18:06
No problem... it just might handle 64 bit Integers down the line, if and when the other browsers support 64 bit. Firefox shows it as 32 bit as does Pale Moon... haven't checked Chromium/Chrome and the rest yet.

**Comment by sebaro** [comment] 2016-08-15 18:34
I think Javascript must support 64-bit integers, some browsers have non-standard support (Int64/UInt64).

**Closed** 2016-10-10 10:11 UTC
